#!/usr/bin/env python3
import requests
import xml.etree.ElementTree as ET
from datetime import datetime

class ANSI:
    RESET  = '\033[0m'
    RED    = '\033[91m'
    CYAN   = '\033[96m'
    YELLOW = '\033[93m'

URL = 'https://archlinux.org/feeds/news'
RX_DATEFORMAT = '%a, %d %b %Y %H:%M:%S %z'
TX_DATEFORMAT = '%Y-%m-%d'

r = requests.get(URL)
root = ET.fromstring(r.content)

for item in root.find('channel').iter('item'):
    date = datetime.strptime(item.find("pubDate").text, RX_DATEFORMAT)
    date = date.strftime(TX_DATEFORMAT)
    title = item.find("title").text
    link = item.find("link").text

    print(f'{ANSI.RED}* {ANSI.YELLOW}{date}{ANSI.RESET}: {title}')
    print(f'{ANSI.CYAN}  {link}')
