#!/usr/bin/env python3
import sys

def up(n):
    print(n, end='')
    if input() == 'q': return
    up(n+1)


def down(n):
    if (n < 0): return
    print(n, end='')
    if input() == 'q': return
    down(n-1)

try:
    assert len(sys.argv) <= 2
    if len(sys.argv) == 1:
        up(0)
    else:
        n = int(sys.argv[1])
        assert n > 0
        down(n)
except Exception:
    print(f'usage: {sys.argv[0]} [ Positive integer ]')
    exit(1)
except KeyboardInterrupt:
    exit(0)
