#!/bin/bash

theme='window {font: "Fira Code Medium 24";}'

emojis="${0}.csv"

[[ ! -f "$emojis" ]] && echo "Could not open $emojis file!" && exit 1

choice=$(cat "$emojis" | rofi -dmenu -theme-str "$theme" | sed -nE 's/(.*)\t.*/\1/p')

[[ -n "$choice" ]] && echo -n "$choice" | xclip -selection clipboard
