#!/bin/bash

if [[ -z "$1" || -z "$2"  ]]; then
  echo "usage: $(basename "$0") image audio [ output_name ]"
  exit 1
fi

fade_length=5
file_out=${3:-out}

# Get music duration in seconds and then calculate fade-out starting point
duration=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$2")
start_time=$(bc <<< "($duration) / 1 - $fade_length")

# Merge image with audio + apply fade filters
ffmpeg -r 24 -loop 1 -y -i "$1" -i "$2" -c:a copy -vcodec libx264 -t "$duration" -vf "fade=t=in:st=0:d=$fade_length,fade=t=out:st=$start_time:d=$fade_length" "${file_out}.mp4"
