#!/bin/bash

if [[ -z "$1" || -z "$2"  ]]; then
  echo "usage: $(basename $0) image audio"
  exit 1
fi

fade_length=5
name="tmp"

# Merge image with audio
ffmpeg -r 24 -loop 1 -y -i "$1" -i "$2" -c:a copy -r 24 -vcodec libx264 -shortest tmp.mp4

if [[ "$?" != "0" ]]; then
  echo "ffmpeg error, aborting"
  exit 2
fi

# Get video duration in seconds and then calculate fade-out starting point
duration=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 tmp.mp4)
start_time=$(bc <<< "($duration) / 1 - $fade_length")

# Apply fade filters
ffmpeg -y -i tmp.mp4 -vf "fade=t=in:st=0:d=$fade_length,fade=t=out:st=$start_time:d=$fade_length" -c:a copy out.mp4

rm tmp.mp4
