#!/bin/bash

dirname=$(dirname "$0")
basename=$(basename "$0")

script=$(
  find "$dirname" -maxdepth 1 -executable -type f -printf '%f\n' \
  | grep -v "$basename" \
  | dmenu -i -fn 'Fira Code Medium' -nb '#16161C' -nf '#E95678' -sb '#E95678' -sf '#16161C'
)

if [[ $script ]]; then
  alacritty --hold -e "$dirname/$script" &
fi
