#!/bin/bash

# Must be in paired-devices
MAC='C8:3F:26:4A:FA:B4'

notify-send 'XPad bluetooth' 'Attempting to connect...' -u low

bluetoothctl power on
bluetoothctl disconnect $MAC
bluetoothctl connect $MAC
