#!/bin/bash

# Must be in paired-devices
MAC='C8:3F:26:4A:FA:B4'

notify-send 'XPad bluetooth' 'Attempting to connect...' -u low

bluetoothctl power on
bluetoothctl disconnect $MAC
status=$(bluetoothctl connect $MAC)

if [[ $(echo "$status" | grep -i 'fail') ]]; then
  notify-send 'XPad bluetooth' 'Failed to connect' -u low
else
  notify-send 'XPad bluetooth' 'Successfully connected' -u low
fi
